/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VCliente.java
 *
 * Created on 23-ene-2011, 1:47:51
 */

package GUI_user;

import Clases.Cliente;
import Clases.Material;
import Listas.ListaClientes;
import Listas.ListaMateriales;
import java.awt.Cursor;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author Diego
 */
public class VMaterial extends javax.swing.JFrame {
            String bandera = "Modificar";
            ListaMateriales  listaMateriales = new ListaMateriales() ;
            List<Integer> Lista_seleccionados = new ArrayList<Integer>();
            int borrar_fila ;

    /** Creates new form VCliente */
    public VMaterial() {
        initComponents();
        this.jTextField1.setText("");
        this.jTextField2.setVisible(false);
        this.jTextField2.setText("");
        this.jTable1.enable(false);
         this.jButton2.setEnabled(false);
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jEImagePanel1 = new GUI.JEImagePanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Buscar por ID :");

        jTextField1.setText("");

        jLabel3.setText("");

        jTextField2.setText("");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null}
            },
            new String [] {
                "ID Material", "Nombre", "Costo", "Descripcion", "Cantidad"/*, "Tipo"*/
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("   Buscar Material");

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Ingresar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Mostrar todo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Salir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jEImagePanel1Layout = new javax.swing.GroupLayout(jEImagePanel1);
        jEImagePanel1.setLayout(jEImagePanel1Layout);
        jEImagePanel1Layout.setHorizontalGroup(
            jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEImagePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jEImagePanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap())
                    .addGroup(jEImagePanel1Layout.createSequentialGroup()
                        .addGroup(jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jEImagePanel1Layout.createSequentialGroup()
                                .addGap(349, 349, 349)
                                .addComponent(jLabel1))
                            .addGroup(jEImagePanel1Layout.createSequentialGroup()
                                .addGroup(jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1988, 1988, 1988))))
            .addGroup(jEImagePanel1Layout.createSequentialGroup()
                .addGap(830, 830, 830)
                .addComponent(jButton6)
                .addContainerGap(1934, Short.MAX_VALUE))
        );
        jEImagePanel1Layout.setVerticalGroup(
            jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEImagePanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jEImagePanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5)
                        .addGap(49, 49, 49))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jEImagePanel1Layout.createSequentialGroup()
                .addContainerGap(582, Short.MAX_VALUE)
                .addComponent(jButton6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jEImagePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 919, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jEImagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
}

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
      Material m = new Material();
      this.listaMateriales.clear();
      this.limpiarTable();
      this.Lista_seleccionados.clear();

        try {
            // TODO add your handling code here:


            m = Material.buscar_material(this.jTextField1.getText());
            this.listaMateriales.add(m);
            for(int i =0 ; i < this.listaMateriales.size();i++){


            this.jTable1.setValueAt(listaMateriales.get(i).getIdMaterial(), i, 0);
            this.jTable1.setValueAt(listaMateriales.get(i).getDescripcionM(), i, 1);
            this.jTable1.setValueAt(listaMateriales.get(i).getCantidad(), i, 4);
            this.jTable1.setValueAt(listaMateriales.get(i).getNombreM(), i, 3);
            this.jTable1.setValueAt(listaMateriales.get(i).getCosto(), i, 2);
            //this.jTable1.setValueAt(listaMateriales.get(i).getTipo(), i, 5);

        }



        } catch (SQLException ex) {
            Logger.getLogger(VBuscar_Material.class.getName()).log(Level.SEVERE, null, ex);
        }


    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:dfd
        VIngresar_Material i_c = new VIngresar_Material();
        i_c.setVisible(true);




    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        if(bandera == "Modificar"){
        this.jTable1.enable(true);
        this.jButton1.setEnabled(false);
        this.jButton2.setEnabled(true);
        this.jButton4.setEnabled(false);
        this.jButton5.setEnabled(false);
        this.jButton6.setEnabled(false);
       this.jButton3.setText("Listo");
       bandera = "Listo" ;
            }else{
         bandera = "Modificar" ;
        this.jButton3.setText("Modificar");
        this.jTable1.enable(false);
        this.jButton1.setEnabled(true);
        this.jButton2.setEnabled(false);
        this.jButton4.setEnabled(true);
        this.jButton5.setEnabled(true);
        this.jButton6.setEnabled(true);

        for(int i = 0 ; i < Lista_seleccionados.size(); i++){
            Material m = new Material((String)this.jTable1.getValueAt(Lista_seleccionados.get(i), 0),(String)this.jTable1.getValueAt(Lista_seleccionados.get(i), 1),
                    (String) this.jTable1.getValueAt(Lista_seleccionados.get(i), 2),(Float)this.jTable1.getValueAt(Lista_seleccionados.get(i), 3) ,(String) this.jTable1.getValueAt(Lista_seleccionados.get(i), 4), (String) this.jTable1.getValueAt(Lista_seleccionados.get(i), 5));
                try {
                    m.Modificar_material(m);
                } catch (SQLException ex) {
                    Logger.getLogger(VMaterial.class.getName()).log(Level.SEVERE, null, ex);
                }
        }




        }
       //System.out.println( this.jTable1.getSelectedRow());

// System.out.println(this.jTable1.getValueAt(0, 0));




    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.listaMateriales.clear();
        try {
            listaMateriales = Material.Mostrar_materiales(listaMateriales);

        for(int i =0 ; i < this.listaMateriales.size();i++){

            this.jTable1.setValueAt(listaMateriales.get(i).getIdMaterial(), i, 0);
            this.jTable1.setValueAt(listaMateriales.get(i).getDescripcionM(), i, 1);
            this.jTable1.setValueAt(listaMateriales.get(i).getCosto(), i, 2);
            this.jTable1.setValueAt(listaMateriales.get(i).getNombreM(), i, 3);
            this.jTable1.setValueAt(listaMateriales.get(i).getCantidad(), i, 4);
            //this.jTable1.setValueAt(listaMateriales.get(i).getTipo(), i, 5);
        }
            } catch (SQLException ex) {
            Logger.getLogger(VMaterial.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:

    }

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:

        if(listaMateriales.size()>this.jTable1.getSelectedRow()&&this.jTable1.getSelectedRow()>=0&&!(Lista_seleccionados.contains(this.jTable1.getSelectedRow())) ){
        Lista_seleccionados.add( this.jTable1.getSelectedRow());

        }

    }

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.dispose();

    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.borrar_fila = this.jTable1.getSelectedRow();
        try {
            Material.borrar_material( (String)this.jTable1.getValueAt(this.borrar_fila, 0));
            this.limpiarFila(this.borrar_fila);

        } catch (SQLException ex) {

        }



    }

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:

    }

private void limpiarTable(){

for(int i=0;i<this.jTable1.getRowCount();i++){
for(int j =0 ; j<this.jTable1.getColumnCount();j++){

    this.jTable1.setValueAt("", i, j);
}
}



}

private void limpiarFila(int fila){


for(int j =0 ; j<this.jTable1.getColumnCount();j++){

    this.jTable1.setValueAt("", fila , j);
}

if(this.Lista_seleccionados.contains(fila)){

    int d = this.Lista_seleccionados.indexOf(this.borrar_fila);
    this.Lista_seleccionados.remove(d);
}


}

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VMaterial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private GUI.JEImagePanel jEImagePanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration

}
