/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * vIngresarEmpleado.java
 *
 * Created on 12/01/2011, 10:13:12 AM
 */

package GUI;

import Clases.Validaciones;
import java.sql.SQLException;

/**
 *
 * @author ricardo
 */
public class detalleEmpleado extends javax.swing.JFrame {

    /** Creates new form vIngresarEmpleado */
    public detalleEmpleado(String cedula,String nombre,String apellido,String departamento,String direccion,String tipo,String telefono,String usuario,String pass,boolean si_no) {
        initComponents();
        this.cedulaEmpleado.setEditable(si_no);
        this.cedulaEmpleado.setText(cedula);
        this.nombreEmpleado.setEditable(si_no);
        this.nombreEmpleado.setText(nombre);
        this.apellidoEmpleado.setEditable(si_no);
        this.apellidoEmpleado.setText(apellido);
        this.domicilioEmpleado.setEditable(si_no);
        this.domicilioEmpleado.setText(direccion);
        this.telefonoempleado.setEditable(si_no);
        this.telefonoempleado.setText(telefono);
        this.departamentoEmpleado.setEditable(si_no);
        this.departamentoEmpleado.setText(departamento);
        this.jTextFieldUser.setEditable(si_no);
        this.jTextFieldUser.setText(usuario);
        this.jTextFieldPass.setEditable(si_no);
        this.jTextFieldPass.setText(pass);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jEImagePanel1 = new GUI.JEImagePanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreEmpleado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        apellidoEmpleado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cedulaEmpleado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sectorEmpleado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        domicilioEmpleado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        telefonoempleado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        departamentoEmpleado = new javax.swing.JTextField();
        IEbotonIngresar = new javax.swing.JButton();
        IEbotonCancelar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jTextFieldPass = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo Empleado");

        jEImagePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/creating-energy-spheres-photoshop.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18));
        jLabel1.setForeground(new java.awt.Color(251, 241, 241));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Detalle de Empleado");

        jLabel2.setForeground(new java.awt.Color(255, 250, 250));
        jLabel2.setText("Nombre");

        nombreEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreEmpleadoKeyTyped(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(251, 249, 249));
        jLabel3.setText("Apellido");

        apellidoEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apellidoEmpleadoKeyTyped(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(246, 242, 242));
        jLabel4.setText("Cedula");

        cedulaEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaEmpleadoActionPerformed(evt);
            }
        });
        cedulaEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cedulaEmpleadoKeyTyped(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(248, 244, 244));
        jLabel5.setText("Sector");

        sectorEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sectorEmpleadoKeyTyped(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(246, 238, 238));
        jLabel6.setText("Direccion");

        domicilioEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                domicilioEmpleadoKeyTyped(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(252, 240, 240));
        jLabel7.setText("Telefono");

        telefonoempleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonoempleadoKeyTyped(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(254, 242, 242));
        jLabel8.setText("Tipo");

        jLabel9.setForeground(new java.awt.Color(244, 240, 240));
        jLabel9.setText("Departamento");

        departamentoEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                departamentoEmpleadoKeyTyped(evt);
            }
        });

        IEbotonIngresar.setText("Ingresar");

        IEbotonCancelar.setText("Cancelar");
        IEbotonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IEbotonCancelarActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(250, 243, 243));
        jLabel10.setText("User");

        jLabel11.setForeground(new java.awt.Color(255, 250, 250));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Password");

        javax.swing.GroupLayout jEImagePanel1Layout = new javax.swing.GroupLayout(jEImagePanel1);
        jEImagePanel1.setLayout(jEImagePanel1Layout);
        jEImagePanel1Layout.setHorizontalGroup(
            jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEImagePanel1Layout.createSequentialGroup()
                .addGroup(jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jEImagePanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(nombreEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE))
                    .addGroup(jEImagePanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jEImagePanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(apellidoEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE))
                            .addComponent(jLabel3)))
                    .addGroup(jEImagePanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                            .addGroup(jEImagePanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(140, 140, 140))))
                    .addGroup(jEImagePanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jEImagePanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(cedulaEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                                .addComponent(sectorEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jEImagePanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 281, Short.MAX_VALUE)
                                .addComponent(jLabel5))))
                    .addGroup(jEImagePanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jEImagePanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(domicilioEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE))
                    .addGroup(jEImagePanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jEImagePanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(telefonoempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addGroup(jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)))
                    .addGroup(jEImagePanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jEImagePanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(departamentoEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE))
                    .addGroup(jEImagePanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jEImagePanel1Layout.createSequentialGroup()
                                .addGroup(jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jEImagePanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jTextFieldUser))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jEImagePanel1Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(IEbotonIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                                .addGroup(jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldPass)
                                    .addComponent(IEbotonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                            .addGroup(jEImagePanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jEImagePanel1Layout.setVerticalGroup(
            jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEImagePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apellidoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cedulaEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sectorEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(domicilioEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonoempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(departamentoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IEbotonIngresar)
                    .addComponent(IEbotonCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEImagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jEImagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IEbotonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IEbotonCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_IEbotonCancelarActionPerformed

    private void cedulaEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaEmpleadoActionPerformed

    private void cedulaEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cedulaEmpleadoKeyTyped
        // TODO add your handling code here:
        Validaciones.SoloNumeros(evt, cedulaEmpleado);
    }//GEN-LAST:event_cedulaEmpleadoKeyTyped

    private void telefonoempleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoempleadoKeyTyped
        // TODO add your handling code here:
        Validaciones.SoloNumeros(evt, telefonoempleado);
    }//GEN-LAST:event_telefonoempleadoKeyTyped

    private void nombreEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreEmpleadoKeyTyped
        // TODO add your handling code here:
        Validaciones.SoloLetras(evt, nombreEmpleado);
    }//GEN-LAST:event_nombreEmpleadoKeyTyped

    private void apellidoEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidoEmpleadoKeyTyped
        // TODO add your handling code here:
        Validaciones.SoloLetras(evt, apellidoEmpleado);
    }//GEN-LAST:event_apellidoEmpleadoKeyTyped

    private void sectorEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sectorEmpleadoKeyTyped
        // TODO add your handling code here:
        Validaciones.SoloLetras(evt, sectorEmpleado);
    }//GEN-LAST:event_sectorEmpleadoKeyTyped

    private void domicilioEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_domicilioEmpleadoKeyTyped
        // TODO add your handling code here:
        Validaciones.SoloLetras(evt, domicilioEmpleado);
    }//GEN-LAST:event_domicilioEmpleadoKeyTyped

    private void departamentoEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_departamentoEmpleadoKeyTyped
        // TODO add your handling code here:
        Validaciones.SoloLetras(evt, departamentoEmpleado);
    }//GEN-LAST:event_departamentoEmpleadoKeyTyped

    /**
    * @param args the command line arguments
    */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IEbotonCancelar;
    private javax.swing.JButton IEbotonIngresar;
    private javax.swing.JTextField apellidoEmpleado;
    private javax.swing.JTextField cedulaEmpleado;
    private javax.swing.JTextField departamentoEmpleado;
    private javax.swing.JTextField domicilioEmpleado;
    private GUI.JEImagePanel jEImagePanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldPass;
    private javax.swing.JTextField jTextFieldUser;
    private javax.swing.JTextField nombreEmpleado;
    private javax.swing.JTextField sectorEmpleado;
    private javax.swing.JTextField telefonoempleado;
    // End of variables declaration//GEN-END:variables

}
