/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * verEmpleados.java
 *
 * Created on 26/01/2011, 09:59:52 AM
 */

package GUI;

import Clases.Empleado;
import Clases.Validaciones;
import Listas.ListaEmpleados;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ricardo
 */
public class verEmpleados extends javax.swing.JFrame {


      ListaEmpleados listaEmpleados = new ListaEmpleados();
    int seleccionados;
    List<Integer> Lista_seleccionados = new ArrayList<Integer>();
    String bandera = "Modificar";
        int borrar_fila ;
    /** Creates new form verEmpleados */
    public verEmpleados() {
        initComponents();

    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jEImagePanel1 = new GUI.JEImagePanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de empleados");

        jLabel1.setText("Empleado");

        jLabel2.setText("Ingrese user ");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jButton1.setText("Ingresar ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Modificar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Eliminar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Mostrar todos");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "User", "Nombre", "Apellido", "Cedula","Tipo","Telefono","Domicilio","Departamento","Pass"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jEImagePanel1Layout = new javax.swing.GroupLayout(jEImagePanel1);
        jEImagePanel1.setLayout(jEImagePanel1Layout);
        jEImagePanel1Layout.setHorizontalGroup(
            jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEImagePanel1Layout.createSequentialGroup()
                .addGroup(jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jEImagePanel1Layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(jLabel1))
                    .addGroup(jEImagePanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jEImagePanel1Layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(jTextField1))
                                .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jEImagePanel1Layout.setVerticalGroup(
            jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEImagePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jEImagePanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(54, 54, 54)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6))
                    .addComponent(jScrollPane1, 0, 0, Short.MAX_VALUE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEImagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEImagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        // TODO add your handling code here:
        if(listaEmpleados.size()>this.jTable1.getSelectedRow()&&this.jTable1.getSelectedRow()>=0 ){
             if(!(Lista_seleccionados.contains(this.jTable1.getSelectedRow()))){


        Lista_seleccionados.add( this.jTable1.getSelectedRow());
             }
             this.seleccionados = this.jTable1.getSelectedRow();

        }
    }//GEN-LAST:event_jTable1MousePressed

    private void limpiarTable(){

for(int i=0;i<this.jTable1.getRowCount();i++){
for(int j =0 ; j<this.jTable1.getColumnCount();j++){

    this.jTable1.setValueAt("", i, j);
}
}

    }

    private void limpiarFila(int fila){


for(int j =0 ; j<this.jTable1.getColumnCount();j++){

    this.jTable1.setValueAt("", fila , j);
}

if(this.Lista_seleccionados.contains(fila)){

    int d = this.Lista_seleccionados.indexOf(this.borrar_fila);
    this.Lista_seleccionados.remove(d);
}


}

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            vIngresarEmpleado VE = new vIngresarEmpleado();
            VE.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(verEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          Empleado e = new Empleado();
      this.listaEmpleados.clear();
      this.limpiarTable();
      this.Lista_seleccionados.clear();

        try {
            // TODO add your handling code here:


            e = Empleado.buscar_empleado(this.jTextField1.getText());
            this.listaEmpleados.add(e);
            for(int i =0 ; i < this.listaEmpleados.size();i++){


            this.jTable1.setValueAt(listaEmpleados.get(i).getUsuario(), i, 0);
            this.jTable1.setValueAt(listaEmpleados.get(i).getNombre(), i, 1);
            this.jTable1.setValueAt(listaEmpleados.get(i).getApellido(), i, 2);
            this.jTable1.setValueAt(listaEmpleados.get(i).getCedula(), i, 3);
            this.jTable1.setValueAt(listaEmpleados.get(i).getTipo(), i, 4);
            this.jTable1.setValueAt(listaEmpleados.get(i).getTelefono(), i, 5);
            this.jTable1.setValueAt(listaEmpleados.get(i).getDireccion(), i, 6);
            this.jTable1.setValueAt(listaEmpleados.get(i).getDepartamento(), i, 7);
            this.jTable1.setValueAt(listaEmpleados.get(i).getPassword(), i, 8);

        }



        } catch (SQLException ex) {
        Logger.getLogger(verEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        if(bandera == "Modificar"){
        this.jTable1.enable(true);
        this.jButton1.setEnabled(false);
         this.jButton2.setEnabled(false);
          this.jButton5.setEnabled(true);
              this.jButton6.setEnabled(false);


       this.jButton4.setText("Listo");
       bandera = "Listo" ;
            }else{
         bandera = "Modificar" ;
        this.jButton4.setText("Modificar");
        this.jTable1.enable(false);
        this.jButton1.setEnabled(true);
         this.jButton2.setEnabled(true);
          this.jButton5.setEnabled(false);
              this.jButton6.setEnabled(true);


        for(int i = 0 ; i < Lista_seleccionados.size(); i++){
            Empleado e = new Empleado((String)this.jTable1.getValueAt(Lista_seleccionados.get(i), 0),(String)this.jTable1.getValueAt(Lista_seleccionados.get(i), 8),
                    (String)this.jTable1.getValueAt(Lista_seleccionados.get(i), 1),(String) this.jTable1.getValueAt(Lista_seleccionados.get(i), 2),
                    (String)this.jTable1.getValueAt(Lista_seleccionados.get(i), 3),(String) this.jTable1.getValueAt(Lista_seleccionados.get(i), 6),
                    (String)this.jTable1.getValueAt(Lista_seleccionados.get(i), 5),(String) this.jTable1.getValueAt(Lista_seleccionados.get(i), 7),
                    (String)this.jTable1.getValueAt(Lista_seleccionados.get(i), 4));
                /*new String [] {
        "User", "Nombre", "Apellido", "Cedula","Tipo","Telefono","Domicilio","Departamento","Pass"
    }*/
            try {
                    e.Modificar_empleado(e);
                } catch (SQLException ex) {
                    Logger.getLogger(verEmpleados.class.getName()).log(Level.SEVERE, null, ex);
                }
        }




        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.borrar_fila = this.jTable1.getSelectedRow();
        try {
            Empleado.borrar_empleado( (String)this.jTable1.getValueAt(this.borrar_fila, 0));
            this.limpiarFila(this.borrar_fila);

        } catch (SQLException ex) {

        }
      
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.limpiarTable();
        this.listaEmpleados.clear();
        try {
            listaEmpleados = Empleado.Mostrar_empleados(listaEmpleados);

        for(int i =0 ; i < this.listaEmpleados.size();i++){

            this.jTable1.setValueAt(listaEmpleados.get(i).getUsuario(), i, 0);
            this.jTable1.setValueAt(listaEmpleados.get(i).getNombre(), i, 1);
            this.jTable1.setValueAt(listaEmpleados.get(i).getApellido(), i, 2);
            this.jTable1.setValueAt(listaEmpleados.get(i).getCedula(), i, 3);
            this.jTable1.setValueAt(listaEmpleados.get(i).getTipo(), i, 4);
            this.jTable1.setValueAt(listaEmpleados.get(i).getTelefono(), i, 5);
            this.jTable1.setValueAt(listaEmpleados.get(i).getDireccion(), i, 6);
            this.jTable1.setValueAt(listaEmpleados.get(i).getDepartamento(), i, 7);
            this.jTable1.setValueAt(listaEmpleados.get(i).getPassword(), i, 8);
            

        }
            } catch (SQLException ex) {
            Logger.getLogger(verEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:

       Validaciones.SoloLetras(evt, jTextField1);
    }//GEN-LAST:event_jTextField1KeyTyped


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new verEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private GUI.JEImagePanel jEImagePanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
